version: '3.8'
services:
  node-backend:
    image: node:20
    working_dir: /app
    command: ["npm", "run", "test"]
    volumes:
      - type: bind
        source: .
        target: /app 
    tty: true